version: '3'

services:
  phishing:
    build: .
    ports:
      - 8001:8001
    links:
      - mariadb
    environment:
      - flag=flag{73ad1744f38b68ece51076c7ac77621b}

  mariadb:
    image: mariadb:10.1
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=assassingo
      - MYSQL_DATABASE=phishing
      - MYSQL_USER=phishing
      - MYSQL_PASSWORD=0311
